### ISSUE TITLE
Add first simple protein graph extractor in Java

### ISSUE THREAD

**Issue by LuisFranciscoHS** [bramburger/PathwayProjectQueries#1]
The objective is to add some Java classes to extract simple version of the protein relationship graph.

Two proteins _p1_ and _p2_ will be considered to be related if:

- p1 and p2 belong to the same Complex or Set (DefineSets, OpenSets or CandidateSets)
- p1 and p2 participate in the same reaction; as a separate entity or as a member of a Complex or Set.
    - p1 is Input and p2 is output
    - p1 is catalystActivity and p2 is input
    - p1 is catalystActivity and p2 is output

There will be different weights assigned for every type of relationship, and also depending on the role they play in the reaction. 

Does that sound fine to you @bramburger ?

**Comment by bramburger** [comment]
Yes.

Just some details:

When p1 and p2 belong to the same Complex, they are playing with each other.
When p1 and p2 belong to the same EntitySet they are not playing with each other : they are, independently of each other, playing with the thing the EntitySet is connected to.
That distinction is important.

I think that the positive and negative regulators should also be in there?
I don't know what the specific descriptions are for them, but I wouldn't throw them out at this point.

Does that still sound reasonable for @LuisFranciscoHS ?

**Comment by LuisFranciscoHS** [comment]
Agree 👍  

Regarding the difference between Complex or Set neighbors we can assign different weights to the relationships and then use that to remark both cases. And certainly, all the nodes of the graph will be proteins, so the complexes and sets will be broken down to members.

About the cases for Reaction neighbors, it is extended to consider the following roles of _p1_ and _p2_:
- _p1_ is Input and _p2_ is output
- _p1_ is catalystActivity and _p2_ is input
- _p1_ is catalystActivity and _p2_ is output
- _p1_ is regulator  and _p2_ is input
- _p1_ is regulator and _p2_ is output
- _p1_ is regulatedBy and _p2_ is input
- _p1_ is regulatedBy and _p2_ is output

On the other hand, I need to dig deeper on the meaning and difference of "regulator" and "regulatedBy", to get a better choice for the weights assigned to those relationships. 

Sounds better @bramburger?

**Comment by bramburger** [comment]
From what I have seen, but I can be wrong, it's 
`(PhysicalEntity)<-[:regulator]-(Regulation)<-[:regulatedBy]-(ReactionLikeEvent | CatalystActivity)`
Excuse the abuse of notation. :)

So a `PhysicalEntity `is a `regulator`, and as such a part of the `Regulation`.
But a `ReactionLikeEvent ` or a `CatalystActivity ` can be `regulatedBy ` a `Regulation`, and as such the `Regulation `is a part of the `ReactionLikeEvent `or the `CatalystActivity`.

So what can happen is that a `Reaction `is `regulatedBy `a `Regulation`, and that same `Reaction `has a `CatalystActivity `which is `regulatedBy `a different `Regulation`.
As in what happens when you expand from the thing with dbId:9606537.
